### PR TITLE
Add more DLL support

### PR DESCRIPTION
**Pull request by Bluscream**
* vcruntime140
* vcruntime140_1
* msvcp140 (Needs explicit definition in [UniversalProxyDLL](https://github.com/techiew/UniversalProxyDLL/blob/master/UniversalProxyDLL.h#L13)
* msvcp140_1
* msvcp140_2

### CODE REVIEW

**Comment by techiew** [comment]
I could not get vcruntime140 or vcruntime140_1 to work when I tested with several games and I could not get msvcp140 to build:
image
For the rest I don't think I found a game that imported them.

Did you test and if so which games did it work with? I only tested 64 bit.

**Comment by Bluscream** [comment]
In my case it was the operation harsh doorstop dedicated server running on UE4.

Interesting compile error. I havent had such issues compiling myself mhmm.

**Comment by Bluscream** [comment]
Whats wrong?

**Comment by techiew** [comment]
It's been a while since I tested but I couldn't really get any of the added DLLs to work. 

The vcruntime ones built but only caused a crash when trying to use them. I can't really see any obvious reason why they shouldn't work.

MSVCP didn't build for me and I suspect it's got to do with the export names, as far as I can see the export names are not supposed to have spaces in them. Looking in PE-bear I see the names are displayed as for example: 
`??$_Getvals@_W@?$time_get@DV?$istreambuf_iterator@DU?$char_traits@D@std@@@std@@@std@@IEAAX_WAEBV_Locinfo@1@@Z`

And I couldn't easily find any games that imported msvcp140_1 or msvcp140_2.

**Comment by Bluscream** [comment]
So everyone who needs them needs to use my fork then, i see. Thanks anyway

**Pull request closed without merging**
